spring.application.name=koneko-backend

spring.datasource.url=jdbc:postgresql://localhost:5433/koneko
spring.datasource.username=postgres
spring.datasource.password=${KONEKO_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

koneko.jwt.secret=${KONEKO_JWT_SECRET}
koneko.jwt.expiration=86400000

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=never

