
INSERT INTO care_messages (phase, message) VALUES

('MENSTRUAL', 'Meyi Baccha, aaj thoda extra rest kar lena. Ali says his Pyari deserves a soft and peaceful day 🫂💓'),
('MENSTRUAL', 'Babu, hydration check! Thoda paani pee lo before Ali starts his annoying reminders again 🫂💓'),
('MENSTRUAL', 'Meyi Gudiya, aaj duniya ko thoda side mein rakho and take care of yourself. Ali says so 🌸🫂💓'),
('MENSTRUAL', 'Shota Chick🐥, blanket mein properly cozy ho jao. Ali wants his Pyari warm and comfortable 🫂💓'),
('MENSTRUAL', 'Pyari, kuch achha sa kha lena today. Empty stomach is not allowed when Ali is looking after you 🫂💓'),
('MENSTRUAL', 'Meyi Baccha, your only mission today is comfort, food, water and rest. Ali has officially approved it 🫂💓'),
('MENSTRUAL', 'Babu, please drink some water. Yes, this is Ali bothering you again, but lovingly 🫂💓'),
('MENSTRUAL', 'Meyi Gudiya, if your body asks for rest, listen to it. Ali says no arguing with your body today 🌸🫂💓'),
('MENSTRUAL', 'Shota Babu, wrap yourself in something soft and take a little break. Ali is sending a warm hug 🫂💓'),
('MENSTRUAL', 'Pyari, eat something nourishing today. Ali needs his Gudiya properly powered up 🌸🫂💓'),
('MENSTRUAL', 'Meyi Baccha, Ali loves you very very much. Now come here and take your little hug 🫂💓'),
('MENSTRUAL', 'Pyari, just a little reminder that Ali loves his Gudiya more than she knows 🫂💓'),
('MENSTRUAL', 'Meyi Gudiya, no matter how your day feels, Ali loves you exactly as you are 🫂💓'),
('MENSTRUAL', 'Babu, drink some water and remember one very important thing: Ali loves you endlessly 🫂💓'),
('MENSTRUAL', 'Meyi Baccha, Ali wishes he could wrap you in the softest blanket and say I love you until you fall asleep 🫂💓'),
('MENSTRUAL', 'Shota Chick🐥, today''s care reminder comes with extra love from Ali. I love you, my Pyari 🫂💓'),
('MENSTRUAL', 'Meyi Gudiya, rest peacefully knowing that somewhere Ali is thinking about his Babu and smiling 🫂💓'),
('MENSTRUAL', 'Pyari, Ali loves every version of you, especially the sleepy and cuddly Koneko one 🐱🫂💓'),
('MENSTRUAL', 'Babu, your little reminder for today: eat well, rest well and remember that Ali loves you so much 🫂💓'),
('MENSTRUAL', 'Meyi Baccha, if Ali could send one thing right now, it would be a huge hug with an I love you inside it 🫂💓'),
('MENSTRUAL', 'Meyi Baccha, slow day is still a good day. Ali says you do not have to be productive all the time 🫂💓'),
('MENSTRUAL', 'Babu, water first, then whatever cozy thing makes you happy. Ali has spoken 🐱🫂💓'),
('MENSTRUAL', 'Meyi Gudiya, keep yourself warm and comfy today. Ali says his Pyari gets premium care 🌸🫂💓'),
('MENSTRUAL', 'Shota Chick🐥, take a tiny rest before doing anything else. Ali is watching your energy levels 👀🫂💓'),
('MENSTRUAL', 'Pyari, have a proper meal today, okay? Ali does not want his Babu running on empty 🫂💓'),
('MENSTRUAL', 'Meyi Baccha, drink some water and breathe slowly for a minute. Ali says you deserve a peaceful moment 🌸🫂💓'),
('MENSTRUAL', 'Babu, today you are allowed to be extra lazy. Ali officially gives permission 🫂💓'),
('MENSTRUAL', 'Meyi Gudiya, rest your little body whenever you need to. Ali says no guilt allowed 🫂💓'),
('MENSTRUAL', 'Shota Babu, grab your blanket, drink some water and become a cozy little Koneko 🐱🫂💓'),
('MENSTRUAL', 'Pyari, please take care of your meals today. Ali wants his Meyi Gudiya feeling cared for 🌸🫂💓'),

('MENSTRUAL', 'Meyi Baccha, if today feels heavy, make everything a little slower. Ali is right beside you in spirit 🫂💓'),
('MENSTRUAL', 'Babu, hydration reminder from your unnecessarily caring Ali. Go drink some water now 🫂💓'),
('MENSTRUAL', 'Meyi Gudiya, you deserve flowers, blankets and absolutely zero unnecessary stress today 🌷🫂💓'),
('MENSTRUAL', 'Shota Chick🐥, no pretending you are invincible today. Ali knows his Pyari needs rest 🫂💓'),
('MENSTRUAL', 'Pyari, have something warm and comforting if you feel like it. Ali says comfort comes first 🌸🫂💓'),
('MENSTRUAL', 'Meyi Baccha, close your eyes for a few minutes and let yourself relax. Ali is sending a soft hug 🫂💓'),
('MENSTRUAL', 'Babu, please keep water nearby today. Your personal annoying reminder system, also known as Ali, insists 🫂💓'),
('MENSTRUAL', 'Meyi Gudiya, be gentle with yourself today. Ali says his Pyari never needs to earn rest 🫂💓'),
('MENSTRUAL', 'Shota Babu, eat properly and then get comfy. Ali has assigned you a very serious mission: take care 🐥🫂💓'),
('MENSTRUAL', 'Pyari, if you feel tired, rest without feeling guilty. Ali says tired Babu gets extra softness today 🫂💓'),

('MENSTRUAL', 'Meyi Baccha, drink your water before you forget. Ali knows his Gudiya sometimes needs reminders 🫂💓'),
('MENSTRUAL', 'Babu, today can be a blanket-and-food kind of day. Ali fully supports this lifestyle 🫂💓'),
('MENSTRUAL', 'Meyi Gudiya, take a peaceful little break and let your mind breathe. Ali says you deserve it 🌸🫂💓'),
('MENSTRUAL', 'Shota Chick🐥, your body is working hard, so please give it some kindness too. Ali says so 🫂💓'),
('MENSTRUAL', 'Pyari, have some water and a proper meal today. Ali is checking both boxes for his Babu 🫂💓'),
('MENSTRUAL', 'Meyi Baccha, no unnecessary stress today. If something can wait, let it wait. Ali says rest first 🫂💓'),
('MENSTRUAL', 'Babu, go find your coziest corner and relax for a while. Ali is sending his Pyari a giant hug 🫂💓'),
('MENSTRUAL', 'Meyi Gudiya, flowers for you because today you deserve a little extra softness 🌷🫂💓'),
('MENSTRUAL', 'Shota Babu, please eat something before becoming a tiny hungry Koneko 🐱 Ali says this is important 🫂💓'),
('MENSTRUAL', 'Pyari, drink some water, get comfortable and let Ali worry about you a little today 🫂💓'),

('MENSTRUAL', 'Meyi Baccha, you do not need to rush anything today. Ali says slow and cozy is perfectly fine 🫂💓'),
('MENSTRUAL', 'Babu, reminder: water exists and Ali would like you to drink some 🫂💓'),
('MENSTRUAL', 'Meyi Gudiya, take care of your body like someone very precious. Ali says you are exactly that 🌸🫂💓'),
('MENSTRUAL', 'Shota Chick🐥, rest those little wings today. Ali says his Pyari needs a softer schedule 🫂💓'),
('MENSTRUAL', 'Pyari, have a nice meal and then give yourself some quiet time. Ali is sending love and a hug 🫂💓'),
('MENSTRUAL', 'Meyi Baccha, cozy blanket, water bottle and peaceful music sounds like a good plan. Ali approves 🫂💓'),
('MENSTRUAL', 'Babu, if you need extra rest today, take it. Ali says there is no need to feel bad about it 🫂💓'),
('MENSTRUAL', 'Meyi Gudiya, remember that taking care of yourself is also an achievement. Ali is proud of his Pyari 🌸🫂💓'),
('MENSTRUAL', 'Shota Babu, go drink some water before Ali sends another reminder. You have been warned 🐥🫂💓'),
('MENSTRUAL', 'Pyari, finish your water, eat something nice and get some rest. Ali wants his Babu comfortable 🫂💓'),



('FOLLICULAR', 'Meyi Gudiya, look at you getting your energy back! Ali says his Pyari is entering little sunshine mode 🌸💓'),
('FOLLICULAR', 'Shota Chick🐥, where did all this energy come from? Ali is slightly suspicious 👀🌸'),
('FOLLICULAR', 'Babu, drink some water and then go enjoy your day. Ali says his Gudiya has places to sparkle ✨💓'),
('FOLLICULAR', 'Meyi Baccha, today feels like a little adventure day. Ali says go make some cute memories 🌸🫂💓'),
('FOLLICULAR', 'Pyari, hydrate yourself before that unstoppable energy starts causing trouble. Ali knows you 🐥💓'),
('FOLLICULAR', 'Meyi Gudiya, you are officially allowed to be extra playful today. Ali is watching though 👀💓'),
('FOLLICULAR', 'Shota Babu, eat something good and then go conquer your tiny kingdom. Ali approves 🐱💓'),
('FOLLICULAR', 'Babu, your energy is suspiciously cute today. Ali may need to investigate 👀🌸💓'),
('FOLLICULAR', 'Meyi Baccha, drink some water and keep that pretty little energy going. Ali says so 🫂💓'),
('FOLLICULAR', 'Pyari, go do something that makes you smile today. Ali wants his Gudiya happy 🌸💓'),
('FOLLICULAR', 'Meyi Gudiya, Ali loves you and unfortunately that means you are stuck with his annoying reminders forever 🫂💓'),
('FOLLICULAR', 'Shota Chick🐥, go enjoy your day, little troublemaker. Ali loves you more than all your mischief 💓'),
('FOLLICULAR', 'Babu, your daily dose of Ali has arrived: drink water and remember I love you 🫂💓'),
('FOLLICULAR', 'Meyi Baccha, Ali loves that cute energetic version of you. Now go be adorable somewhere 🌸💓'),
('FOLLICULAR', 'Pyari, Ali just wanted to interrupt your day for one tiny reason: I love you, Meyi Gudiya 🫂💓'),
('FOLLICULAR', 'Meyi Gudiya, you are cute, chaotic and completely loved by Ali. Please continue being yourself 👀🫂💓'),
('FOLLICULAR', 'Shota Babu🐥, hydration reminder sponsored by Ali''s unlimited love for his Pyari 🫂💓'),
('FOLLICULAR', 'Babu, Ali hopes you smile today because he loves that little smile of his Gudiya so much 💓'),
('FOLLICULAR', 'Meyi Baccha, go have fun today. Ali loves seeing his Pyari happy and full of energy 🌸🫂💓'),
('FOLLICULAR', 'Pyari, one final interruption from Ali: drink your water, eat properly and remember that I love you 💓'),
('FOLLICULAR', 'Shota Chick🐥, no disappearing into your own little world without telling Ali first 👀🫂💓'),
('FOLLICULAR', 'Meyi Gudiya, today is for fresh energy, tiny adventures and a little mischief. Ali approves all three 🌸💓'),
('FOLLICULAR', 'Babu, hydration check! Your annoying Ali has arrived with another water reminder 🫂💓'),
('FOLLICULAR', 'Meyi Baccha, you have energy today, so please spend some of it doing something fun 🌸💓'),
('FOLLICULAR', 'Pyari, eat properly today. Ali cannot have his Shota Chick🐥 running around on an empty stomach 🫂💓'),
('FOLLICULAR', 'Meyi Gudiya, you seem extra bright today. Ali is blaming the sunshine, obviously 🌸✨💓'),
('FOLLICULAR', 'Babu, drink some water and stretch a little. Ali says your tiny body deserves maintenance too 🫂💓'),
('FOLLICULAR', 'Shota Babu, go enjoy your day, but remember Ali is still allowed to annoy you about water 🐥💓'),
('FOLLICULAR', 'Meyi Baccha, your mood deserves something fun today. Ali says choose something that makes you giggle 🌸💓'),
('FOLLICULAR', 'Pyari, little reminder from Ali: take a break between all that energetic Gudiya activity 🫂💓'),

('FOLLICULAR', 'Meyi Gudiya, today you can be cute, chaotic and slightly annoying. Ali has accepted the challenge 👀💓'),
('FOLLICULAR', 'Shota Chick🐥, drink water first, then continue being the little troublemaker Ali adores 🫂💓'),
('FOLLICULAR', 'Babu, fresh day, fresh energy, fresh flowers for my Pyari 🌷 Ali says enjoy it 💓'),
('FOLLICULAR', 'Meyi Baccha, do not forget food while you are busy being energetic. Ali is putting his foot down 🫂💓'),
('FOLLICULAR', 'Pyari, your energy seems upgraded today. Ali is proud but also slightly concerned about the chaos 😭💓'),
('FOLLICULAR', 'Meyi Gudiya, go outside for a little fresh air if you can. Ali says sunshine suits his Pyari 🌸💓'),
('FOLLICULAR', 'Babu, hydration time. Yes, again. No, Ali is not going to stop reminding you 🫂💓'),
('FOLLICULAR', 'Shota Babu, your little wings are ready today 🐥 Go enjoy something fun, says Ali 🌸💓'),
('FOLLICULAR', 'Meyi Baccha, smile a little today. Ali says that tiny smile is officially part of his daily requirements 💓'),
('FOLLICULAR', 'Pyari, take your happy energy and do something lovely with it. Ali is cheering for his Gudiya 🫂💓'),

('FOLLICULAR', 'Meyi Gudiya, you have permission to be playful today, but water is still compulsory. Signed: Ali 🫂💓'),
('FOLLICULAR', 'Shota Chick🐥, please eat something before your energy turns into full Koneko chaos 🐱💓'),
('FOLLICULAR', 'Babu, today is looking soft and bright. Ali says go enjoy the little things 🌸💓'),
('FOLLICULAR', 'Meyi Baccha, take a tiny break and drink some water. Even energetic Gudiya needs recharge time 🫂💓'),
('FOLLICULAR', 'Pyari, Ali has a very important request: smile, hydrate and do not overwork yourself 💓'),
('FOLLICULAR', 'Meyi Gudiya, your playful mood has been noticed. Ali is keeping an eye on his little troublemaker 👀💓'),
('FOLLICULAR', 'Shota Babu, eat something nice today and keep your energy happy. Ali says his Pyari deserves it 🫂💓'),
('FOLLICULAR', 'Babu, fresh flowers and fresh water for a fresh little Gudiya 🌷🫂💓'),
('FOLLICULAR', 'Meyi Baccha, if you have been waiting for a fun little plan, today might be a lovely day for it 🌸 Ali says go 💓'),
('FOLLICULAR', 'Pyari, drink water before Ali has to personally file a complaint against your water bottle 🫂💓'),

('FOLLICULAR', 'Meyi Gudiya, you are allowed to enjoy your good energy today. Ali says just remember to rest too 🌸🫂💓'),
('FOLLICULAR', 'Shota Chick🐥, tiny hydration break! Then you may return to your mischievous activities 💓'),
('FOLLICULAR', 'Babu, Ali says eat well today because energetic little Koneko needs fuel 🐱🫂💓'),
('FOLLICULAR', 'Meyi Baccha, go find something that makes today feel special. Ali says little joys count 🌸💓'),
('FOLLICULAR', 'Pyari, you look like you are ready to conquer the day. Ali says take your water bottle with you 🫂💓'),
('FOLLICULAR', 'Meyi Gudiya, playful mood detected. Ali is preparing himself for whatever mischief comes next 👀💓'),
('FOLLICULAR', 'Shota Babu, take a little fresh-air break today. Ali says his Pyari deserves some sunshine 🌷💓'),
('FOLLICULAR', 'Babu, drink water, eat something nice and then go be your adorable chaotic self. Ali permits it 🫂💓'),
('FOLLICULAR', 'Meyi Baccha, today is a good day to laugh a little more. Ali wants his Gudiya smiling 💓'),
('FOLLICULAR', 'Pyari, keep that cute energy but do not forget your little rest breaks. Ali is still your reminder department 🫂💓'),


('OVULATION', 'Meyi Gudiya… there is something dangerously charming about you today 👀🌙 Ali is keeping a very close eye on his Pyari 🫂💓'),
('OVULATION', 'Pyari, tonight feels a little more magical than usual. Ali says his Gudiya might be carrying a tiny spell 🌙✨💓'),
('OVULATION', 'Shota Chick🐥, behave yourself today… or at least pretend to. Ali knows that mischievous look 👀🌙💓'),
('OVULATION', 'Meyi Baccha, drink some water before you get lost in your own little fantasy world. Ali still has to take care of you 🫂💓'),
('OVULATION', 'Babu… today you have that mysterious little energy. Ali is wondering what kind of trouble his Pyari is planning 👀🌙💓'),
('OVULATION', 'Meyi Gudiya, if tonight feels like a moonlit story, just remember Ali is somewhere in the story too 🌙🫂💓'),
('OVULATION', 'Pyari, take care of yourself today. Even the most enchanting Gudiya needs water, food and rest 🫂💓'),
('OVULATION', 'Shota Babu🐥, you are looking suspiciously magical today. Ali may have to guard his little Koneko from the moon 🌙💓'),
('OVULATION', 'Meyi Baccha, hydrate yourself before your mysterious little energy takes over the kingdom. Ali insists 🫂💓'),
('OVULATION', 'Babu, there is a little mischief in the air today… Ali can almost see it hiding behind his Gudiya''s smile 👀🌙💓'),

('OVULATION', 'Meyi Gudiya, tonight you may feel like the main character in Ali''s favorite little fantasy 🌙✨🫂💓'),
('OVULATION', 'Pyari, keep some water nearby. Ali refuses to let his enchanting Babu forget basic care 🫂💓'),
('OVULATION', 'Shota Chick🐥, that playful mood is dangerous territory. Ali is watching from the shadows 👀🌙💓'),
('OVULATION', 'Meyi Baccha, eat something good today. Even magical little creatures need proper fuel 🐥🌙🫂💓'),
('OVULATION', 'Babu… maybe it is the moon, maybe it is your mood, but Ali says you seem unusually captivating tonight 🌙💓'),
('OVULATION', 'Meyi Gudiya, take a quiet moment tonight and enjoy your own little world. Ali says make it beautiful 🌙🌸💓'),
('OVULATION', 'Pyari, hydration first. Then you may continue being mysteriously adorable and slightly dangerous 👀🫂💓'),
('OVULATION', 'Shota Babu, Ali has a feeling your mischievous side is awake today. Please keep it cute 🐥🌙💓'),
('OVULATION', 'Meyi Baccha, you have been warned: too much cuteness may cause Ali to become unnecessarily clingy 🫂💓'),
('OVULATION', 'Babu, there is something soft and mysterious about tonight. Ali says his Pyari should enjoy the little magic 🌙✨💓'),
('OVULATION', 'Meyi Gudiya… Ali loves you a little dangerously today. That mysterious little smile is not helping 👀🌙🫂💓'),
('OVULATION', 'Pyari, there is something about you tonight that makes Ali want to stay close a little longer 🌙🫂💓'),
('OVULATION', 'Babu… if Ali had a favorite fantasy, it would probably involve his Gudiya smiling at him like that 👀🌙💓'),
('OVULATION', 'Meyi Baccha, drink your water first… then you can continue making Ali fall for you all over again 🌙🫂💓'),
('OVULATION', 'Shota Chick🐥, Ali loves you, but that mischievous little look is making it very difficult for him to behave 👀💓'),
('OVULATION', 'Meyi Gudiya, tonight feels magical, and Ali says his favorite part of the magic is simply you 🌙✨🫂💓'),
('OVULATION', 'Pyari, Ali loves his mysterious little Koneko. Now drink some water before you enchant everyone around you 🐱🌙🫂💓'),
('OVULATION', 'Babu… you have no idea how much Ali loves that cute little person hiding behind all that mischief 👀🫂💓'),
('OVULATION', 'Meyi Baccha, if this were a moonlit story, Ali would still choose his Pyari as the favorite part 🌙🫂💓'),
('OVULATION', 'Meyi Gudiya, a little reminder from Ali under the imaginary moonlight: I love you, my beautiful little troublemaker 🌙💓'),


('OVULATION', 'Meyi Gudiya, if your day feels extra bright and dreamy, let yourself enjoy it. Ali is sending a moonlit hug 🌙🫂💓'),
('OVULATION', 'Pyari, drink some water and take a little rest. Ali needs his favorite little Koneko properly cared for 🐱🫂💓'),
('OVULATION', 'Shota Chick🐥, stop looking so innocent. Ali knows there is mischief hiding somewhere 👀💓'),
('OVULATION', 'Meyi Baccha, tonight is for soft lights, peaceful thoughts and a little fantasy. Ali says enjoy 🌙✨💓'),
('OVULATION', 'Babu… if Ali had to describe today, he would say: sweet, mysterious and slightly dangerous. Just like his Gudiya 👀🌙💓'),
('OVULATION', 'Meyi Gudiya, eat properly today and save some energy for your beautiful little adventures 🌸 Ali says so 🫂💓'),
('OVULATION', 'Pyari, keep yourself hydrated while you are busy being enchanting. Ali is still watching over his Babu 🫂💓'),
('OVULATION', 'Shota Babu🐥, moonlight, mischief and that tiny smile of yours sound like trouble. Ali is prepared 🌙👀💓'),
('OVULATION', 'Meyi Baccha, you deserve to feel beautiful and cared for today. Ali says never forget that 🫂💓'),
('OVULATION', 'Babu, a little flower for the little enchantress 🌷🌙 Ali says his Pyari deserves something pretty 💓'),

('OVULATION', 'Meyi Gudiya, today feels like one of those nights where everything becomes a little more dreamy 🌙✨ Ali says enjoy it 💓'),
('OVULATION', 'Pyari, please drink your water before you start wandering around in your fantasy kingdom 🫂💓'),
('OVULATION', 'Shota Chick🐥, Ali has officially detected extra mischief. Please behave… or at least stay adorable 👀💓'),
('OVULATION', 'Meyi Baccha, rest when you need it. Even an enchanting little Gudiya needs her peaceful moments 🌙🫂💓'),
('OVULATION', 'Babu… there is a little mystery in your smile today. Ali is curious, but he will let his Pyari keep her secrets 👀🌙💓'),
('OVULATION', 'Meyi Gudiya, take care of yourself like the precious little character you are in Ali''s favorite story 🌙🫂💓'),
('OVULATION', 'Pyari, food and water first, fantasy later. Ali has to keep his magical Babu functioning properly 🫂💓'),
('OVULATION', 'Shota Babu🐥, if the moon starts giving you mischievous ideas tonight, blame it on Ali''s Gudiya 🌙👀💓'),
('OVULATION', 'Meyi Baccha, you seem full of a strange little sparkle today. Ali says keep it, but stay hydrated ✨🫂💓'),
('OVULATION', 'Babu, tonight belongs to soft music, moonlight and a little harmless mischief. Ali approves 🌙💓'),

('OVULATION', 'Meyi Gudiya, your cute little chaos has a different flavor today. Ali is trying very hard not to stare 👀💓'),
('OVULATION', 'Pyari, take a slow breath, drink some water and enjoy your evening. Ali says his Babu deserves peaceful magic 🌙🫂💓'),
('OVULATION', 'Shota Chick🐥, your mischievous aura has been reported to Ali. Investigation is ongoing 👀🌙💓'),
('OVULATION', 'Meyi Baccha, have something nice to eat and let yourself enjoy the dreamy mood today 🌸🌙 Ali says so 💓'),
('OVULATION', 'Babu… maybe the stars are behaving differently tonight, because Ali says his Gudiya seems extra captivating 🌙✨💓'),
('OVULATION', 'Meyi Gudiya, keep yourself comfortable, hydrated and happy. Ali wants his little enchantress cared for 🫂💓'),
('OVULATION', 'Pyari, tonight you are allowed to be soft, mysterious and a tiny bit mischievous 👀🌙 Ali can handle it 💓'),
('OVULATION', 'Shota Babu🐥, go drink some water before your magical little brain starts inventing more trouble 🌙🫂💓'),
('OVULATION', 'Meyi Baccha, whatever kind of day you are having, Ali wants you feeling safe, cared for and a little spoiled 🫂💓'),
('OVULATION', 'Babu, sleep well tonight, little moon creature. Ali says even his most enchanting Pyari needs proper rest 🌙🫂💓'),

('LUTEAL', 'Meyi Baccha, if everything feels a little too much today, come back to the basics: water, food and rest. Ali says so 🫂💓'),
('LUTEAL', 'Pyari, you do not have to handle everything today. Ali says his Babu can slow down 🫂💓'),
('LUTEAL', 'Meyi Gudiya, come here, tiny Koneko. Today calls for extra softness and a long hug 🐱🫂💓'),
('LUTEAL', 'Shota Chick🐥, drink some water before you start getting grumpy at the entire universe. Ali knows you 🫂💓'),
('LUTEAL', 'Babu, eat something comforting today. Ali says his Pyari deserves a little cozy happiness 🌸🫂💓'),
('LUTEAL', 'Meyi Baccha, if your mood feels strange today, be gentle with yourself. Ali is not judging his Gudiya 🫂💓'),
('LUTEAL', 'Pyari, rest a little more if you need it. Ali says productivity can wait for his Babu 🫂💓'),
('LUTEAL', 'Meyi Gudiya, hydration check from your very annoying but caring Ali. Please drink some water 🫂💓'),
('LUTEAL', 'Shota Babu, today is a blanket, snack and rest kind of day. Ali fully supports this plan 🐥🫂💓'),
('LUTEAL', 'Babu, whatever mood you are in today, Ali still wants his Pyari to be gentle with herself 🫂💓'),
('LUTEAL', 'Meyi Baccha, come here. Ali loves you and thinks you deserve the biggest hug today 🫂💓'),
('LUTEAL', 'Pyari, whatever kind of mood today brings, Ali still loves his Babu exactly the same 🫂💓'),
('LUTEAL', 'Meyi Gudiya, you never have to be perfect for Ali to love you. Just be his little Koneko 🐱🫂💓'),
('LUTEAL', 'Babu, drink some water and remember that Ali is completely and hopelessly fond of his Pyari 🫂💓'),
('LUTEAL', 'Meyi Baccha, if today feels heavy, borrow some comfort from Ali''s love and take a little rest 🫂💓'),
('LUTEAL', 'Shota Chick🐥, Ali loves you even on your grumpy days. Especially when you need an extra hug 🫂💓'),
('LUTEAL', 'Meyi Gudiya, no matter how messy the day gets, Ali''s love for his Babu does not disappear 🫂💓'),
('LUTEAL', 'Pyari, eat something nice and rest. Ali loves his little Gudiya and wants her feeling cared for 🫂💓'),
('LUTEAL', 'Babu, tonight just relax. Ali loves you, misses you and is sending one unnecessarily large hug 🫂💓'),
('LUTEAL', 'Meyi Baccha, sleep peacefully tonight knowing that Ali loves his Pyari more than this little notification can ever explain 🫂💓'),
('LUTEAL', 'Meyi Baccha, you are allowed to need extra comfort. Ali says come closer and take a little rest 🫂💓'),
('LUTEAL', 'Pyari, eat properly today. Ali refuses to let his little Gudiya survive on random snacks alone 🫂💓'),
('LUTEAL', 'Meyi Gudiya, flowers for you because sometimes a tiny pretty thing can make a heavy day softer 🌷🫂💓'),
('LUTEAL', 'Shota Chick🐥, please drink water. Your Ali has entered reminder mode again 🫂💓'),
('LUTEAL', 'Babu, if you feel like doing absolutely nothing today, that is allowed. Ali gives full permission 🫂💓'),
('LUTEAL', 'Meyi Baccha, take your time today. Ali says his Pyari does not need to rush anything 🌸🫂💓'),
('LUTEAL', 'Meyi Gudiya, your feelings deserve kindness too. Ali says do not be too hard on yourself 🫂💓'),
('LUTEAL', 'Pyari, get something warm, get comfortable and let your little body relax. Ali is sending a hug 🫂💓'),
('LUTEAL', 'Shota Babu🐥, no fighting with the water bottle today. Drink up, says Ali 🫂💓'),
('LUTEAL', 'Babu, Ali says today can be a quiet little day. No pressure, just care, food and rest 🫂💓'),

('LUTEAL', 'Meyi Baccha, if you need a little extra reassurance today, remember that Ali is always rooting for his Pyari 🫂💓'),
('LUTEAL', 'Meyi Gudiya, take a small break before you get overwhelmed. Ali says breathe and relax 🌸🫂💓'),
('LUTEAL', 'Pyari, hydration first. Then find your favorite cozy spot and stay there for a while 🫂💓'),
('LUTEAL', 'Shota Chick🐥, you are not required to be cheerful every minute. Ali says you can simply be you 🫂💓'),
('LUTEAL', 'Mela Shota Babu, have a proper meal today. Ali wants his little Koneko warm, fed and comfortable 🐱🫂💓'),
('LUTEAL', 'Meyi Baccha, if today feels emotionally heavy, make your world smaller and softer. Ali says that is okay 🫂💓'),
('LUTEAL', 'Meyi Gudiya, your annoying Ali is here again: water please. Yes, I know you heard this already 🫂💓'),
('LUTEAL', 'Pyari, rest your mind for a little while. You do not need to solve everything today, says Ali 🫂💓'),
('LUTEAL', 'Shota Babu, get cozy and let the day move slowly. Ali says his Gudiya deserves peace 🌙🫂💓'),
('LUTEAL', 'Babu, eat something nice and give yourself permission to be extra soft today. Ali approves 🫂💓'),

('LUTEAL', 'Meyi Baccha, no unnecessary guilt today. Rest is not laziness, especially for Ali''s Pyari 🫂💓'),
('LUTEAL', 'Meyi Gudiya, take a little hydration break. Ali is counting this as his daily duty 🫂💓'),
('LUTEAL', 'Pyari, if you are feeling clingy today, that is perfectly okay. Ali says come closer 🫂💓'),
('LUTEAL', 'Shota Chick🐥, blanket secured? Water secured? Snack secured? Ali is conducting the inspection 👀🫂💓'),
('LUTEAL', 'Babu, today does not need to be perfect. Ali only wants his Gudiya to take care of herself 🫂💓'),
('LUTEAL', 'Meyi Baccha, have a little quiet time today. Ali says your mind deserves some breathing space 🌸🫂💓'),
('LUTEAL', 'Meyi Gudiya, if something can wait until tomorrow, let it wait. Ali says tonight is for comfort 🌙🫂💓'),
('LUTEAL', 'Pyari, please drink some water and eat something proper. Ali is being annoyingly responsible again 🫂💓'),
('LUTEAL', 'Shota Babu🐥, you are allowed to be a tiny sleepy Koneko today. Ali says no objections 🐱🫂💓'),
('LUTEAL', 'Babu, come back to your cozy little corner and rest. Ali says his Pyari has done enough for today 🫂💓'),

('LUTEAL', 'Meyi Baccha, your mood can change and that is okay. Ali is still here, caring for his Gudiya 🫂💓'),
('LUTEAL', 'Meyi Gudiya, drink some water, take a deep breath and give yourself a little kindness 🌸 Ali says so 🫂💓'),
('LUTEAL', 'Pyari, today is a good day for comfort food, soft blankets and absolutely no unnecessary stress 🫂💓'),
('LUTEAL', 'Shota Chick🐥, please stop pretending you do not need rest. Ali knows better 🫂💓'),
('LUTEAL', 'Babu, if you need to sleep a little earlier tonight, do it. Ali says his Pyari needs proper rest 🌙🫂💓'),
('LUTEAL', 'Meyi Baccha, you deserve patience from yourself too. Ali says do not bully his Gudiya today 🫂💓'),
('LUTEAL', 'Meyi Gudiya, a little flower and a little hug for you. Ali says today should feel softer 🌷🫂💓'),
('LUTEAL', 'Pyari, water check one more time. Ali knows his Babu might be pretending not to hear him 👀🫂💓'),
('LUTEAL', 'Shota Babu🐥, get your cozy things ready and let yourself slow down tonight. Ali says rest well 🌙🫂💓'),
('LUTEAL', 'Meyi Baccha, whatever today brought you, finish it gently. Ali wants his Pyari safe, rested and cared for 🫂💓');